import { BiCheckCircle, BiIdCard } from 'react-icons/bi';
import {
  Box,
  FormControl,
  FormHelperText,
  FormErrorMessage,
  FormLabel,
  Image,
  Input,
  Stack,
  Button,
  InputGroup,
  InputLeftElement,
  useToast,
  Icon,
} from '@chakra-ui/react';
import Head from 'next/head';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import loginSchema from '@schemas/login.schema';
import { signIn } from 'next-auth/react';
import { NextPageAuth } from '@/types/AuthPages';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const Login: NextPageAuth = () => {
  const toast = useToast();
  const router = useRouter();
  const {
    handleSubmit,
    register,
    formState: { errors, touchedFields, isSubmitting },
  } = useForm({
    mode: 'onBlur',
    defaultValues: { id: '' },
    resolver: yupResolver(loginSchema),
  });

  useEffect(() => {
    if (router.query.error) {
      toast({
        title: 'Combinación inválida',
        description:
          'No se pudo iniciar sesión, verifique su documento de identidad.',
        isClosable: true,
        status: 'error',
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const onSubmit = async (form: any) => {
    signIn('credentials', {
      id: form.id,
      callbackUrl: '/',
    });
  };

  return (
    <>
      <Head>
        <title>Zona Activa | Activo Urbano</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box bg="blackAlpha.900" width="full" height="full">
        <Stack
          align="center"
          justify="center"
          style={{ width: '100%', height: '100%', padding: '0 4px' }}
        >
          <Box
            bg="whiteAlpha.100"
            borderTopColor="yellow.600"
            borderTopWidth="5px"
            borderRadius="lg"
            boxShadow="base"
            overflow="hidden"
            w={['100%', '480px', '720px']}
          >
            <Link href="https://www.activourbano.com.co/" passHref>
              <Image
                id="au-logo"
                src="/au_240.png"
                aria-label="Ir a Activo Urbano"
                alt="Logo Activo Urbano"
                style={{
                  margin: '0 auto',
                  padding: '1.5rem',
                  cursor: 'pointer',
                }}
                role="link"
              />
            </Link>
            <Box p="6">
              <form id="login-form" onSubmit={handleSubmit(onSubmit)}>
                <FormControl isInvalid={!!errors.id}>
                  <FormLabel htmlFor="user-id" color="white">
                    Ingrese el número de cédula del titular del contrato
                  </FormLabel>
                  <InputGroup>
                    <InputLeftElement pointerEvents="none">
                      <Icon as={BiIdCard} color="gray.300" />
                    </InputLeftElement>
                    <Input
                      id="user-id"
                      type="text"
                      color="white"
                      placeholder="#########"
                      isInvalid={!!errors.id}
                      rounded="full"
                      {...register('id')}
                    />
                  </InputGroup>
                  {errors.id ? (
                    <FormErrorMessage>{errors.id?.message}</FormErrorMessage>
                  ) : touchedFields.id ? (
                    <FormHelperText color="green.300">
                      <Icon as={BiCheckCircle} />
                      <span> Tu documento de identidad es válido.</span>
                    </FormHelperText>
                  ) : (
                    <FormHelperText color="gray.400">&nbsp;</FormHelperText>
                  )}
                </FormControl>
                <Button
                  mt={4}
                  isFullWidth
                  colorScheme="yellow"
                  bgColor="yellow.500"
                  _hover={{ backgroundColor: 'yellow.600' }}
                  isLoading={isSubmitting}
                  type="submit"
                  rounded="full"
                >
                  Iniciar Sesión
                </Button>
              </form>
            </Box>
          </Box>
        </Stack>
      </Box>
    </>
  );
};

Login.auth = false;

export default Login;
