import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import { NextPageAuth } from '@/types/AuthPages';

const Home: NextPageAuth = () => {
  return (
    <>
      <Head>
        <title>Zona Activa | Activo Urbano</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box bg="gray.700" width="full" height="full"></Box>
    </>
  );
};

Home.auth = true;

export default Home;
