import { AtSignIcon, LockIcon, ViewIcon, ViewOffIcon } from '@chakra-ui/icons';
import {
  Box,
  FormControl,
  FormHelperText,
  FormErrorMessage,
  FormLabel,
  Image,
  Input,
  Stack,
  Button,
  InputGroup,
  InputLeftElement,
  InputRightElement,
  IconButton,
  useToast,
} from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import loginSchema from '@schema/login.schema';
import ky from '@lib/ky';

const Home: NextPage = () => {
  const toast = useToast();
  const {
    handleSubmit,
    register,
    formState: { errors, touchedFields, isSubmitting },
  } = useForm({
    mode: 'onBlur',
    defaultValues: { user: '', password: '' },
    resolver: yupResolver(loginSchema),
  });

  const [showPass, setShowPass] = useState(false);

  const onSubmit = async (form: any) => {
    try {
      const res = await ky
        .post('Login/Login/ActivoUrbano', {
          json: { username: form.user, password: form.password },
        })
        .json();
      console.log(res);
    } catch (error) {
      toast({
        title: 'Combinación inválida',
        description:
          'No se pudo iniciar sesión, verifique su usuario y contraseña',
        isClosable: true,
        status: 'error',
      });
    }
  };

  const onFailure = (values: any) => {
    console.error(values);
  };

  return (
    <>
      <Head>
        <title>Zona Activa | Activo Urbano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="favicon.png" />
      </Head>
      <Box bg="gray.700" width="full" height="full">
        <Stack
          align="center"
          justify="center"
          style={{ width: '100%', height: '100%' }}
        >
          <Box
            bg="gray.800"
            borderTopColor="yellow.600"
            borderTopWidth="5px"
            borderRadius="lg"
            boxShadow="base"
            overflow="hidden"
            w={['100%', '480px', '640px', '720px']}
          >
            <Image
              src="/au_240.png"
              alt="Activo Urbano"
              style={{ margin: '0 auto', padding: '1.5rem' }}
            />
            <Box p="6">
              <form onSubmit={handleSubmit(onSubmit, onFailure)}>
                <FormControl isInvalid={!!errors.user}>
                  <FormLabel htmlFor="user" color="white">
                    Usuario
                  </FormLabel>
                  <InputGroup>
                    <InputLeftElement pointerEvents="none">
                      <AtSignIcon color="gray.300" />
                    </InputLeftElement>
                    <Input
                      id="user"
                      type="text"
                      color="white"
                      placeholder="zonaactiva"
                      {...register('user')}
                    />
                  </InputGroup>
                  {errors.user ? (
                    <FormErrorMessage>{errors.user?.message}</FormErrorMessage>
                  ) : (
                    <FormHelperText
                      color={touchedFields.user ? 'green.300' : 'gray.400'}
                    >
                      Ingresa tu usuario registrado en Zona Activa
                    </FormHelperText>
                  )}
                </FormControl>
                <FormControl isInvalid={!!errors.password} mt="4">
                  <FormLabel htmlFor="password" color="white">
                    Contraseña
                  </FormLabel>
                  <InputGroup>
                    <InputLeftElement pointerEvents="none">
                      <LockIcon color="gray.300" />
                    </InputLeftElement>
                    <Input
                      id="password"
                      type={showPass ? 'text' : 'password'}
                      color="white"
                      placeholder="******"
                      {...register('password')}
                    />
                    <InputRightElement>
                      <IconButton
                        aria-label="Mostrar/Esconder contraseña"
                        colorScheme="yellow"
                        variant="ghost"
                        size="sm"
                        icon={
                          showPass ? (
                            <ViewOffIcon w={5} h={5} />
                          ) : (
                            <ViewIcon w={5} h={5} />
                          )
                        }
                        onClick={() => setShowPass(!showPass)}
                      ></IconButton>
                    </InputRightElement>
                  </InputGroup>
                  {errors.password ? (
                    <FormErrorMessage>
                      {errors.password?.message}
                    </FormErrorMessage>
                  ) : (
                    <FormHelperText
                      color={touchedFields.password ? 'green.300' : 'gray.400'}
                    >
                      La contraseña debe contener 6 caracteres
                    </FormHelperText>
                  )}
                </FormControl>
                <Button
                  mt={4}
                  isFullWidth
                  colorScheme="yellow"
                  bgColor="yellow.500"
                  _hover={{ backgroundColor: 'yellow.600' }}
                  isLoading={isSubmitting}
                  type="submit"
                >
                  Iniciar Sesión
                </Button>
              </form>
            </Box>
          </Box>
        </Stack>
      </Box>
    </>
  );
};

export default Home;
